#!/bin/zsh

# zsh aliases

# weather
function weather() {curl wttr.in/${1:-Vancouver}}

# show and hide files
alias show-files="defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app"
alias hide-files="defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app"

# Base64
function encode() {echo -n ${1} | base64}
function decode() {echo -n ${1} | base64 --decode}

# kill all processes on a port
function kill-port() {
    local port=$1
    local pid=$(lsof -t -i:$port | awk 'NR==2 {print $2}')
    if [[ -z $pid ]]; then
        echo "No process found on port $port"
    else
        kill -9 $pid
        echo "Killed process $pid on port $port"
    fi
}

# nvim to vim
alias vim="nvim"

# bat (cat on steroids)
alias cat="bat --paging=never --theme=Coldark-Dark --plain"

# eza (ls on steroids)
alias ls="eza --color=always --icons=always --git"

# zoxide (cd on steroids)
alias cd="z"

# python
alias python="python3"

# laravel
alias art="php artisan" 
alias fresh="php artisan migrate:fresh --seed"
alias sail="sh $([ -f sail ] && echo sail || echo vendor/bin/sail)"
