#!/bin/bash

# weather
function weather() {
    curl wttr.in/${1:-Berlin}
}

# Base64
function encode() {
    echo -n ${1} | base64
}

function decode() {
    echo -n ${1} | base64 --decode
}

# ip
function ip {
    if [[ $# -eq 0 ]] ; then
        echo 'Please provide the URL to look up.'
        return
    fi

    echo `dig +short $1 | awk '{ print ; exit }'`
}
