# source antigen location
source /opt/homebrew/share/antigen/antigen.zsh

# load oh-my-zsh library
antigen init $HOME/.antigenrc

# Default editor
export EDITOR='vim'

# Aliases
source $HOME/.dotfiles/files/zsh_aliases

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Path
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Custom Path
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/.dotfiles/bin"

# Node Version Manager (NVM)
source $(brew --prefix nvm)/nvm.sh
export NVM_DIR="$HOME/.nvm"

# Python version manager (pyenv)
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Java version manager (jenv)
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Zsh
export PATH="/usr/local/opt/ncurses/bin:$PATH"
