# source antigen location
source /opt/homebrew/share/antigen/antigen.zsh

# Path
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

# load oh-my-zsh library
antigen init $HOME/.antigenrc

# Default editor
export EDITOR='vim'

# Starship prompt config
export STARSHIP_CONFIG="$HOME/.dotfiles/files/starship.toml"

# Aliases
source $HOME/.dotfiles/files/zsh_aliases

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Custom Path
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/.dotfiles/bin"

# Node Version Manager (NVM)
source $(brew --prefix nvm)/nvm.sh
export NVM_DIR="$HOME/.nvm"

# Python version manager (pyenv)
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Java version manager (jenv)
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Ruby version manager
eval "$(frum init)"

# Zsh
export PATH="/usr/local/opt/ncurses/bin:$PATH"

# FZF
eval "$(fzf --zsh)"
source $HOME/.dotfiles/files/fzf.sh

# zoxide
eval "$(zoxide init zsh)"

