name: dotfiles smoke test

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: .dotfiles
    - name: Execute full install
      run:  ./install.sh
