name: dotfiles smoke test

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy to home directory
      run: cp /Users/runner/work/dotfiles/dotfiles /Users/runner/.dotfiles

    - name: Execute full install
      run: ./install.sh
